name: Lint Python
on: [push, pull_request]
jobs:
  lint-python:
    name: lint-python
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install flake8
      run: |
        pip install flake8 flake8-import-order
    - name: Lint python with flake8
      run: |
        flake8 . --max-complexity=10 --statistics
